Img_processing: Add optional visuals
KamaTechOrg/VehicleComputingSimulator pull request #100
Opened 2024-10-08 08:00 UTC by TziporaGoldshmidt

2024-10-08 19:32 UTC, ChedvaErblich requested changes

2024-10-08 19:32 UTC, ChedvaErblich commented on img_processing/CMakeLists.txt
> +option(SHOW_FRAMES "Enable showing frames" OFF)
Do you want it to be off by default? 
Just checking, go with whatever works best for you.

2024-10-08 19:32 UTC, ChedvaErblich commented on img_processing/src/manager.cpp
> +        if (key == 27) {
This isn't directly related, but it caught my eye. The value '27' is unclear consider defining it as a variable with a meaningful name or, or, at least, adding a comment to explain it. Please make this change in a separate commit.

2024-10-09 07:07 UTC, TziporaGoldshmidt commented on img_processing/CMakeLists.txt
> +option(SHOW_FRAMES "Enable showing frames" OFF)
changed to on

2024-10-09 07:07 UTC, TziporaGoldshmidt commented on img_processing/src/manager.cpp
> +        if (key == 27) {
i added #define ESC 27

2024-10-09 07:12 UTC, merged