Img_processing: Add optional travel status
KamaTechOrg/VehicleComputingSimulator pull request #103
Opened 2024-10-08 10:21 UTC by TziporaGoldshmidt

2024-10-08 23:38 UTC, ChedvaErblich requested changes
Please have someone else review the code, and after she approves it, I'll push it in.

2024-10-08 23:38 UTC, ChedvaErblich commented on img_processing/src/manager.cpp
> +    // Open the JSON file
same line twice

2024-10-08 23:38 UTC, ChedvaErblich commented on img_processing/src/manager.cpp
> +        std::cerr << "Failed to open the file." << std::endl;
Why/?
Use the logger

2024-10-08 23:38 UTC, ChedvaErblich commented on img_processing/data.json
This file should be given via run time, your code should support any video,
if you need this for testing, put this file under the test dir

2024-10-08 23:38 UTC, ChedvaErblich commented on img_processing/src/manager.cpp
>  #include "alert.h"
Includes are not in the right order

2024-10-09 07:21 UTC, TziporaGoldshmidt commented on img_processing/src/manager.cpp
> +    // Open the JSON file
done

2024-10-09 07:21 UTC, TziporaGoldshmidt commented on img_processing/src/manager.cpp
> +        std::cerr << "Failed to open the file." << std::endl;
done

2024-10-09 07:21 UTC, TziporaGoldshmidt commented on img_processing/src/manager.cpp
>  #include "alert.h"
done

2024-10-09 14:20 UTC, closed without merging