Integration gui control
KamaTechOrg/VehicleComputingSimulator pull request #81
Opened 2024-09-26 10:03 UTC by s7932

2024-09-30 19:13 UTC, ChedvaErblich requested changes
A few general things

1.When using the logger, we need to be mindful of its impact on performance and decide carefully when to use debug versus info levels. Each log write incurs a time cost, so logging frequently in info mode for basic flows that are called many times during runtime can slow down performance. On the other hand, using debug allows us to gather detailed information during development or debugging, without impacting production performance, as debug logs won’t be written when running in production mode.
2. Make sure you don't have long lines beyond the convention definitions.
3. I want someone else to review the code and approve it before we push it in.
4. There are many edge cases to check regarding the validity of the JSON files concerning the deletion and addition of blocks. I noticed you've addressed this in the code. Please take some time to ensure you cover all cases, and it would be great if you could write down the list of them in a file and share it with us.
5. What about the tests?

2024-09-30 19:13 UTC, ChedvaErblich commented on gui/include/main_window.h
> +    QPushButton *openDependencySelectionProjectButton;  // Button to open the second project
Do not mix variables and functions. First, write declarations for all the functions, and then for the variables. Move the declaration to the appropriate place.

Add add a blank line between the functions and the parameters

2024-09-30 19:13 UTC, ChedvaErblich commented on gui/src/main_window.cpp
> +    // Create the new button to open the Dependency selection project
Add blank line for more readability.

2024-09-30 19:13 UTC, ChedvaErblich commented on gui/src/main_window.cpp
> +    // Connect the button's click signal to the function that opens the second project
Same here

2024-09-30 19:13 UTC, ChedvaErblich commented on gui/src/main_window.cpp
> +    QFile file("sensors.json");
If we are loading a saved simulation, we will have an old file, and that's fine. However, in the case of a new simulation or changes to the existing simulation, the old file will no longer be valid.

We need to understand when it is valid and when it is not.

2024-09-30 19:13 UTC, ChedvaErblich commented on gui/src/main_window.cpp
> +        // Create QFileSystemWatcher to monitor the directory
You have an extra tab, please remove it

2024-09-30 19:13 UTC, ChedvaErblich commented on gui/src/main_window.cpp
> +            guiLogger.logMessage(logger::LogLevel::ERROR,
Error handling?
Do we want to make continue in such a case?

2024-09-30 19:13 UTC, ChedvaErblich commented on gui/src/main_window.cpp
> +             // Hide stop button for the corresponding DraggableSquare
You have an extra tab, please remove it

2024-09-30 19:13 UTC, ChedvaErblich commented on gui/src/main_window.cpp
> +                square->setStopButtonVisible(false);  // Hide the stop button
Is this related to this commit?
if not split it into 2 commits

2024-09-30 19:13 UTC, ChedvaErblich commented on gui/src/main_window.cpp
> +                    // Remove the old proces from the JSON file
The comment should be aligned with the code; you have an extra tab, please remove it

2024-09-30 19:13 UTC, ChedvaErblich commented on gui/src/main_window.cpp
> +                    // Update the JSON file with the new details
Same here,
The comment should be aligned with the code; you have an extra tab please remove it

2024-09-30 19:13 UTC, ChedvaErblich commented on gui/src/main_window.cpp
> +     // Remove the process from the JSON file
here it is one extra space

2024-09-30 19:13 UTC, ChedvaErblich commented on gui/src/main_window.cpp
> +    // Compile the second project
We need o think about it, 
I'm not sure we will need to compile it, we may need to have the project to be compiled before starting

2024-09-30 19:13 UTC, ChedvaErblich commented on gui/src/main_window.cpp
> +        qDebug() << "Failed to compile the second project.";
Consider replacing it with log,
Or do you have a reason for using the qdebug?

2024-09-30 19:13 UTC, ChedvaErblich commented on gui/src/main_window.cpp
> +        qDebug() << "Failed to set execution permissions.";
Same here, can we use the log?

2024-09-30 19:13 UTC, ChedvaErblich commented on gui/src/main_window.cpp
> +        qDebug() << "Second project started successfully with PID:" << pid;
Same here

2024-09-30 19:13 UTC, ChedvaErblich commented on gui/src/main_window.cpp
> +                             "Failed to set execute permissions for script: " + chmodProcess.errorString().toStdString());
I think it's too long line,
Are you using the formater?

2024-09-30 19:13 UTC, ChedvaErblich commented on gui/src/main_window.cpp
> -
Don't remove it :)

2024-09-30 19:13 UTC, ChedvaErblich commented on gui/src/main_window.cpp
> +    chmodArgs << "+x" << scriptPath; // Arguments for chmod
If we use the same logic when running the shell script to compile the project, it might be worth having a general function to handle it, which both functions can call.

2024-09-30 20:42 UTC, s7932 commented on gui/include/main_window.h
> +    QPushButton *openDependencySelectionProjectButton;  // Button to open the second project
DONE

2024-09-30 20:45 UTC, s7932 commented on gui/src/main_window.cpp
> +    // Create the new button to open the Dependency selection project
DONE

2024-09-30 20:46 UTC, s7932 commented on gui/src/main_window.cpp
> +    // Connect the button's click signal to the function that opens the second project
DONE

2024-09-30 20:52 UTC, s7932 commented on gui/src/main_window.cpp
> +        // Create QFileSystemWatcher to monitor the directory
fixed

2024-09-30 20:54 UTC, s7932 commented on gui/src/main_window.cpp
> +             // Hide stop button for the corresponding DraggableSquare
fixed

2024-09-30 20:57 UTC, s7932 commented on gui/src/main_window.cpp
> +                    // Remove the old proces from the JSON file
fixed

2024-09-30 20:58 UTC, s7932 commented on gui/src/main_window.cpp
> +                    // Update the JSON file with the new details
fixed.....

2024-09-30 20:59 UTC, s7932 commented on gui/src/main_window.cpp
> +     // Remove the process from the JSON file
fixed

2024-09-30 21:01 UTC, s7932 commented on gui/src/main_window.cpp
> +    // Compile the second project
I've been thinking about it, and compiling really does take a long time. If we can actually assume we already have it pre-compiled, it would definitely make more sense...

2024-10-01 07:51 UTC, s7932 commented on gui/src/main_window.cpp
> +    chmodArgs << "+x" << scriptPath; // Arguments for chmod
There are some differences, so I will make no changes.

2024-10-01 07:52 UTC, s7932 commented on gui/src/main_window.cpp
> -
Fixed....

2024-10-01 07:53 UTC, s7932 commented on gui/src/main_window.cpp
> +                             "Failed to set execute permissions for script: " + chmodProcess.errorString().toStdString());
o.k. I splited its

2024-10-01 07:57 UTC, s7932 commented on gui/src/main_window.cpp
> +        qDebug() << "Second project started successfully with PID:" << pid;
fixed

2024-10-01 07:58 UTC, s7932 commented on gui/src/main_window.cpp
> +        qDebug() << "Failed to set execution permissions.";
fixed

2024-10-01 07:58 UTC, s7932 commented on gui/src/main_window.cpp
> +        qDebug() << "Failed to compile the second project.";
Fixed, it was only for my development.

2024-10-01 08:11 UTC, s7932 commented on gui/src/main_window.cpp
> +            guiLogger.logMessage(logger::LogLevel::ERROR,
fixed

2024-10-01 08:33 UTC, s7932 commented on gui/src/main_window.cpp
> +    QFile file("sensors.json");
I spoke with Chani and Devorah about their method of saving simulations, and I understood that they save information for each previous simulation. I think I'll leave it like this for now, and an additional task will be to ensure saving a file in the DB for each simulation so it can be loaded later. Therefore, I have no problem deleting an old file in the constructor.

2024-10-01 12:49 UTC, merged