Gui/enable core dump
KamaTechOrg/VehicleComputingSimulator pull request #84
Opened 2024-09-26 23:08 UTC by Tamar-Leibovitz

2024-09-28 18:38 UTC, ChedvaErblich requested changes
Your commit message is a bit long. 
Consider keeping the basic information in the message header and moving the details to the body.
(suggestion: 
GUI: handle process crash

Generate core dump, notify user, stop system if initial process crashes)

One more thing,
When using the logger, we need to be mindful of its impact on performance and decide carefully when to use debug versus info levels. Each log write incurs a time cost, so logging frequently in info mode for basic flows that are called many times during runtime can slow down performance. On the other hand, using debug allows us to gather detailed information during development or debugging, without impacting production performance, as debug logs won’t be written when running in production mode.

2024-09-28 18:38 UTC, ChedvaErblich commented on gui/include/main_window.h
> +    //
Left over? please remove it

2024-09-28 18:38 UTC, ChedvaErblich commented on gui/include/draggable_square.h
> +    QString getDumpFilePath()
It's better to implement the functions in the cpp file

2024-09-28 18:38 UTC, ChedvaErblich commented on gui/include/main_window.h
> +    //
Same here

2024-09-28 18:38 UTC, ChedvaErblich commented on gui/include/main_window.h
> +    void openDialog();
You add by mistake whitespace at the end of the line, 
I  think this is the conflict you see.

2024-09-28 18:38 UTC, ChedvaErblich commented on gui/src/draggable_square.cpp
> +    // layout->setContentsMargins(0, 0, 0, 0);
Why did you comment it out?
if it's unneeded please remove it, unless there is a reason to leave it here

2024-09-28 18:38 UTC, ChedvaErblich commented on gui/src/draggable_square.cpp
> +        glowEffect->setBlurRadius(30);
It's best to avoid using hardcoded numbers (unless they are trivial). Whenever possible, define the numbers to make the code more readable and easier to modify.

2024-09-28 18:38 UTC, ChedvaErblich commented on gui/src/main_window.cpp
> +    // Process *mainProcess =
Why it's commented out?

2024-09-28 18:38 UTC, ChedvaErblich commented on gui/src/main_window.cpp
> +        new Process(id, "HSM", "../src/dummy_program1/CMakeLists.txt", "QEMUPlatform");
Is this change related to your commit?
if it's a fix for previous commits, 
Consider having a separate commit for this

2024-09-28 18:38 UTC, ChedvaErblich commented on gui/src/main_window.cpp
> -
Don't modify other users code if not necessary,
It's right to have a blank line between different snippets of code for more readability

2024-09-28 18:38 UTC, ChedvaErblich commented on gui/log_file.log
Why did you delete this file?

2024-09-28 18:38 UTC, ChedvaErblich commented on gui/src/main_window.cpp
> +                // Hide stop button for the corresponding DraggableSquare
You have an extra tab, remove it.

2024-09-28 18:38 UTC, ChedvaErblich commented on gui/src/main_window.cpp
> +    outFile.close();  // Close the file before running gdb
If you have a long comment it's better to put it in a separate line (or lines) rather than continue it at a new line...

2024-09-28 18:38 UTC, ChedvaErblich commented on gui/src/main_window.cpp
> +            "MainWindow::createBacktrace Backtrace baddddddddddddddd saved to: ");
Edit the log message :).

2024-09-28 18:38 UTC, ChedvaErblich commented on gui/src/main_window.cpp
> -
Same here, don't remove it...

2024-09-28 18:38 UTC, ChedvaErblich commented on gui/src/main_window.cpp
> +            QDir cmakeDir(QFileInfo(executionFilePath).absolutePath());
Why?

2024-09-28 18:38 UTC, ChedvaErblich commented on gui/src/main_window.cpp
>  void MainWindow::runProjects()
Consider splitting this function into smaller ones. It was already quite long, and now it has grown even more.

2024-09-28 18:38 UTC, ChedvaErblich commented on gui/src/main_window.cpp
>      for (DraggableSquare *square : squares) {
Is there a way to do this without deep nesting?

2024-09-28 18:38 UTC, ChedvaErblich commented on gui/test/dummy_program2/main.cpp
> +int main() {
Leave it as it is

2024-09-28 18:38 UTC, ChedvaErblich commented on gui/test/dummy_program2/main.cpp
> +    // std::ifstream file("../config.json");  // Replace with your JSON file name
Why do you commented it out?

2024-09-28 18:38 UTC, ChedvaErblich commented on gui/test/dummy_program2/main.cpp
> +    // json jsonObject;
Why do you commented it out?

2024-09-28 18:38 UTC, ChedvaErblich commented on gui/test/test_main_window.cpp
> +    // void testSetCoreDumpLimit();
Why?

2024-09-28 18:38 UTC, ChedvaErblich commented on gui/test/test_main_window.cpp
> +// void TestMainWindow::testSetCoreDumpLimit()
Why?
if it is due to a bug, 
lets see if we can insert a fix before your commit.

2024-09-28 18:38 UTC, ChedvaErblich commented on gui/test/dummy_program1/main.cpp
What is the reason of removing this file?

2024-09-29 18:36 UTC, Tamar-Leibovitz commented on gui/include/main_window.h
> +    //
I removed

2024-09-29 18:37 UTC, Tamar-Leibovitz commented on gui/include/draggable_square.h
> +    QString getDumpFilePath()
I did it

2024-09-29 18:37 UTC, Tamar-Leibovitz commented on gui/include/main_window.h
> +    //
👍

2024-09-29 18:43 UTC, Tamar-Leibovitz commented on gui/src/draggable_square.cpp
> +    // layout->setContentsMargins(0, 0, 0, 0);
Somebody wrote thoso lines, as general design. but it not correct.
I asked in the channel who did it, but nobody answerd
so I decided to leave it in a comment till somebody will remember what was the idea- to do it general.

2024-09-29 18:53 UTC, Tamar-Leibovitz commented on gui/src/main_window.cpp
> +        new Process(id, "HSM", "../src/dummy_program1/CMakeLists.txt", "QEMUPlatform");
everybody suggest to leave it as it is.
it is not a fix, more comfortable

2024-09-29 19:04 UTC, Tamar-Leibovitz commented on gui/src/main_window.cpp
>      for (DraggableSquare *square : squares) {
I want in the fix commit to seperate to a new function

2024-09-29 19:04 UTC, Tamar-Leibovitz commented on gui/src/main_window.cpp
>  void MainWindow::runProjects()
I want in the fix it in a seperate commit

2024-09-30 16:58 UTC, closed without merging